---
- hosts: control
  become: yes
  tasks:
    - name: install packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - curl
        - tree
        - ncdu
        - vim-nox
        - python-httplib2
