---
# tasks file for mysql
- name: install tools
  apt:
    name: ['python-mysqldb']
    state: present

- name: install mysql-server
  apt: name=mysql-server state=present

- name: ensure mysql listening on all interfaces
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = {{ ansible_eth1.ipv4.address }}"
  notify: restart mysql

- name: ensure mysql started
  service: name=mysql state=started enabled=yes

- name: create database
  mysql_db: name={{ db_name }} state=present

- name: create demo user
  mysql_user: name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL host='{{ db_user_host }}' state=present
